import type { VideoInfo, VideoStream, SubtitleTrack } from '../shared/types';
import type { VideoProvider, ExtractionContext } from './provider-interface';

function generateId(): string {
  return typeof crypto !== 'undefined' && crypto.randomUUID
    ? crypto.randomUUID()
    : 'vimeo-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 10);
}

const VIMEO_URL_RE = /(?:player\.)?vimeo\.com\/(?:video\/)?(\d+)/;
const VIMEO_EMBED_RE = /player\.vimeo\.com\/video\/(\d+)/;

function extractVideoId(url: string): string | null {
  const match = url.match(VIMEO_URL_RE);
  return match ? match[1] : null;
}

interface VimeoProgressive {
  url: string;
  quality: string;
  width: number;
  height: number;
  fps: number;
  mime: string;
}

interface VimeoTextTrack {
  url: string;
  lang: string;
  label: string;
  kind: string;
}

interface VimeoConfig {
  video?: {
    id?: number;
    title?: string;
    duration?: number;
    thumbs?: Record<string, string>;
  };
  request?: {
    files?: {
      progressive?: VimeoProgressive[];
      hls?: {
        cdns?: Record<string, { url: string }>;
        default_cdn?: string;
      };
    };
    text_tracks?: VimeoTextTrack[];
  };
}

async function fetchConfig(videoId: string): Promise<VimeoConfig> {
  const resp = await fetch(`https://player.vimeo.com/video/${videoId}/config`, {
    headers: { Accept: 'application/json' },
  });
  if (!resp.ok) {
    throw new Error(`Vimeo config fetch failed: ${resp.status}`);
  }
  return resp.json() as Promise<VimeoConfig>;
}

const vimeoProvider: VideoProvider = {
  name: 'vimeo',
  displayName: 'Vimeo',
  version: '1.0.0',

  canHandleUrl(url: string): boolean {
    return VIMEO_URL_RE.test(url);
  },

  getEmbedPatterns(): RegExp[] {
    return [VIMEO_EMBED_RE];
  },

  async extractVideoInfo(context: ExtractionContext): Promise<VideoInfo> {
    const videoId = extractVideoId(context.url);
    if (!videoId) {
      throw new Error('Could not extract Vimeo video ID from URL');
    }

    const config = await fetchConfig(videoId);
    const streams: VideoStream[] = [];
    const subtitles: SubtitleTrack[] = [];

    // Progressive MP4 streams
    const progressive = config.request?.files?.progressive ?? [];
    for (const p of progressive) {
      streams.push({
        url: p.url,
        quality: p.quality || `${p.height}p`,
        resolution: `${p.width}x${p.height}`,
        type: 'muxed',
        format: 'mp4',
        frameRate: p.fps ? String(p.fps) : undefined,
      });
    }

    // HLS master playlist
    const hls = config.request?.files?.hls;
    if (hls?.cdns) {
      const cdnKey = hls.default_cdn ?? Object.keys(hls.cdns)[0];
      const hlsUrl = hls.cdns[cdnKey]?.url;
      if (hlsUrl) {
        streams.push({
          url: hlsUrl,
          quality: 'auto (HLS)',
          type: 'muxed',
          format: 'm3u8',
        });
      }
    }

    // Text tracks / subtitles
    const textTracks = config.request?.text_tracks ?? [];
    for (const t of textTracks) {
      const trackUrl = t.url.startsWith('http')
        ? t.url
        : `https://player.vimeo.com${t.url}`;
      subtitles.push({
        url: trackUrl,
        language: t.lang,
        label: t.label,
        format: 'vtt',
        isAutoGenerated: t.kind === 'asr' ? true : t.kind === 'captions' ? false : undefined,
      });
    }

    // Thumbnail — pick the largest available
    let thumbnail: string | undefined;
    const thumbs = config.video?.thumbs;
    if (thumbs) {
      thumbnail = thumbs['1280'] ?? thumbs['960'] ?? thumbs['640'] ?? thumbs['base'] ?? Object.values(thumbs)[0];
    }

    return {
      id: generateId(),
      title: config.video?.title ?? `Vimeo Video ${videoId}`,
      thumbnail,
      duration: config.video?.duration,
      provider: 'vimeo',
      pageUrl: context.pageUrl ?? context.url,
      streams,
      subtitles,
      metadata: { vimeoId: videoId },
    };
  },
};

export default vimeoProvider;
