// Shared TypeScript types for the Video Downloader Extension

export interface VideoStream {
  url: string;
  quality: string;
  resolution?: string;
  bandwidth?: number;
  codec?: string;
  type: 'video' | 'audio' | 'muxed';
  format?: string;
  fileSize?: number;
  frameRate?: string;
}

export interface SubtitleTrack {
  url: string;
  language: string;
  label?: string;
  format: 'vtt' | 'srt' | 'ttml' | 'unknown';
  isAutoGenerated?: boolean;
}

export interface VideoInfo {
  id: string;
  title: string;
  thumbnail?: string;
  duration?: number;
  provider: string;
  pageUrl: string;
  streams: VideoStream[];
  subtitles: SubtitleTrack[];
  metadata?: Record<string, unknown>;
}

export interface DetectedVideo {
  id: string;
  type: 'html5' | 'iframe' | 'stream';
  url: string;
  title?: string;
  thumbnail?: string;
  provider: string;
  tabId?: number;
  frameId?: number;
}

export interface DownloadTask {
  id: string;
  videoInfo: VideoInfo;
  selectedStream: VideoStream;
  audioStream?: VideoStream;
  subtitleTracks?: SubtitleTrack[];
  status: 'pending' | 'downloading' | 'muxing' | 'complete' | 'error';
  progress: number;
  error?: string;
  outputFilename?: string;
  startedAt: number;
  completedAt?: number;
}

export interface ExtensionSettings {
  preferredQuality: 'best' | '1080p' | '720p' | '480p' | '360p';
  autoDetect: boolean;
  downloadSubtitles: boolean;
  showNotifications: boolean;
  enabledProviders: string[];
}

export const DEFAULT_SETTINGS: ExtensionSettings = {
  preferredQuality: 'best',
  autoDetect: true,
  downloadSubtitles: true,
  showNotifications: true,
  enabledProviders: [],
};
