import { createHash } from 'node:crypto';
import { spawn, spawnSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import {
  access,
  mkdir,
  mkdtemp,
  readdir,
  readFile,
  rm,
  stat,
  writeFile,
} from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import process from 'node:process';

const INVALID_FILENAME_CHARS = /[<>:"/\\|?*\x00-\x1F]/g;
const DEFAULT_SUMMARY_MODEL = 'gpt-4.1';
const DEFAULT_TRANSCRIPTION_MODEL = 'gpt-4o-transcribe';
const DEFAULT_CHUNK_CHAR_LIMIT = 9000;
const DEFAULT_CHUNK_DURATION_SECONDS = 12 * 60;
const AUDIO_SEGMENT_SECONDS = 10 * 60;
const SUMMARY_VERSION = 1;
const OPENAI_MAX_RETRIES = 6;

let ffmpegBinary = 'ffmpeg';

type SummaryLanguage = 'bilingual' | 'match' | 'english';
type SourceType = 'subtitle' | 'transcript';
type LessonRunStatus = 'success' | 'skipped' | 'failed' | 'dry-run';
type DocumentKind =
  | 'chapter'
  | 'course'
  | 'ingredients'
  | 'techniques'
  | 'recipes'
  | 'glossary';

interface CliOptions {
  courseRoot: string;
  chapter?: number;
  lesson?: number;
  force: boolean;
  dryRun: boolean;
  model: string;
  transcriptionModel: string;
  language: SummaryLanguage;
  withVisuals: boolean;
}

interface CourseNode {
  title: string;
  courseRoot: string;
  summaryRoot: string;
  chapters: ChapterNode[];
}

interface ChapterNode {
  order: number;
  title: string;
  dir: string;
  lessons: LessonNode[];
}

interface LessonNode {
  courseTitle: string;
  chapterOrder: number;
  chapterTitle: string;
  lessonOrder: number;
  title: string;
  videoPath: string;
  subtitlePaths: string[];
  lessonKey: string;
  summaryJsonPath: string;
  summaryMarkdownPath: string;
}

interface SourceCue {
  startSeconds: number;
  endSeconds: number;
  text: string;
  sourceType: SourceType;
}

interface LessonSource {
  sourceType: SourceType;
  subtitlePath?: string;
  transcriptSegments?: string[];
  languageHint: string;
  autoGeneratedHint: boolean;
  charCount: number;
  cueCount: number;
  qualityNotes: string[];
  cues: SourceCue[];
}

interface PreparedChunk {
  index: number;
  startSeconds: number;
  endSeconds: number;
  sourceType: SourceType;
  text: string;
  cueCount: number;
}

interface TopicEntry {
  name: string;
  detail: string;
  evidence: string[];
}

interface RecipeEntry {
  title: string;
  context: string;
  ingredients: string[];
  quantities: string[];
  steps: string[];
  techniqueNotes: string[];
  platingNotes: string[];
  substitutions: string[];
  evidence: string[];
}

interface ChunkSummary {
  chunkIndex: number;
  startTimestamp: string;
  endTimestamp: string;
  conciseOverview: string;
  concepts: TopicEntry[];
  ingredients: TopicEntry[];
  techniques: TopicEntry[];
  tools: TopicEntry[];
  recipes: RecipeEntry[];
  caveats: string[];
  facts: string[];
  inferences: string[];
  glossary: TopicEntry[];
}

interface LessonSummaryData {
  metadata: {
    version: number;
    courseTitle: string;
    chapterOrder: number;
    chapterTitle: string;
    lessonOrder: number;
    lessonTitle: string;
    lessonKey: string;
    videoPath: string;
    subtitlePaths: string[];
    primaryLanguage: string;
    requestedLanguageMode: SummaryLanguage;
  };
  source: {
    sourceType: SourceType;
    sourcePath?: string;
    transcriptSegments?: string[];
    cueCount: number;
    charCount: number;
    languageHint: string;
    autoGeneratedHint: boolean;
    qualityNotes: string[];
  };
  timelineSegments: Array<{
    chunkIndex: number;
    startTimestamp: string;
    endTimestamp: string;
    sourceType: SourceType;
    summary: string;
  }>;
  conciseOverview: {
    primary: string;
    english: string;
  };
  detailedSummary: {
    primary: string;
    english: string;
  };
  keyTakeaways: string[];
  ingredientNotes: TopicEntry[];
  techniqueNotes: TopicEntry[];
  equipmentNotes: TopicEntry[];
  recipes: RecipeEntry[];
  warnings: string[];
  ambiguities: string[];
  facts: string[];
  inferences: string[];
  glossary: TopicEntry[];
}

interface LessonManifestEntry {
  lessonKey: string;
  lessonTitle: string;
  chapterOrder: number;
  lessonOrder: number;
  sourceSignature: string;
  summaryJsonPath: string;
  summaryMarkdownPath: string;
  sourceType?: SourceType;
  status: LessonRunStatus;
  updatedAt: string;
  error?: string;
}

interface DocumentManifestEntry {
  key: string;
  kind: DocumentKind;
  signature: string;
  path: string;
  status: LessonRunStatus;
  updatedAt: string;
}

interface SummaryManifest {
  version: number;
  generatedAt: string;
  courseRoot: string;
  courseTitle: string;
  summaryRoot: string;
  options: {
    model: string;
    transcriptionModel: string;
    language: SummaryLanguage;
    withVisuals: boolean;
  };
  lessons: LessonManifestEntry[];
  documents: DocumentManifestEntry[];
}

interface OpenAiChatMessage {
  role: 'system' | 'user';
  content: string;
}

function printUsage(): void {
  console.log(`Course Summarizer

Usage:
  npm.cmd run course:summarize -- --course-root <path> [options]

Required:
  --course-root

Options:
  --chapter <n>
  --lesson <n>
  --force
  --dry-run
  --model <name>
  --transcription-model <name>
  --language bilingual|match|english
  --with-visuals

Environment:
  OPENAI_API_KEY        Required for non-dry-run summarization
  OPENAI_BASE_URL       Optional, defaults to https://api.openai.com/v1
`);
}

function normalizeText(value: string | null | undefined): string {
  return (value ?? '').replace(/\s+/g, ' ').trim();
}

function sanitizePathSegment(value: string, fallback: string): string {
  const sanitized = normalizeText(value)
    .replace(INVALID_FILENAME_CHARS, '_')
    .replace(/\s+/g, ' ')
    .trim();
  return sanitized || fallback;
}

function formatIndex(value: number): string {
  return String(value).padStart(2, '0');
}

function stringifyError(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

function sha256(input: string): string {
  return createHash('sha256').update(input).digest('hex');
}

function timestampFromSeconds(totalSeconds: number): string {
  const safeSeconds = Math.max(0, Math.floor(totalSeconds));
  const hours = Math.floor(safeSeconds / 3600);
  const minutes = Math.floor((safeSeconds % 3600) / 60);
  const seconds = safeSeconds % 60;
  return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
}

function detectPrimaryLanguage(text: string): string {
  const hebrewCount = (text.match(/[\u0590-\u05FF]/g) || []).length;
  const latinCount = (text.match(/[A-Za-z]/g) || []).length;
  if (hebrewCount > latinCount * 0.25) {
    return 'he';
  }
  return 'en';
}

function parsePositiveInteger(name: string, value: string | undefined): number | undefined {
  if (value === undefined) return undefined;
  const parsed = Number.parseInt(value, 10);
  if (!Number.isFinite(parsed) || parsed < 1) {
    throw new Error(`--${name} must be a positive integer.`);
  }
  return parsed;
}

function parseArgs(argv: string[]): CliOptions {
  const flags = new Set<string>();
  const values = new Map<string, string>();

  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    if (!argument.startsWith('--')) {
      throw new Error(`Unexpected argument: ${argument}`);
    }

    const [rawKey, inlineValue] = argument.slice(2).split('=', 2);
    if (rawKey === 'force' || rawKey === 'dry-run' || rawKey === 'with-visuals') {
      flags.add(rawKey);
      continue;
    }

    const value = inlineValue ?? argv[index + 1];
    if (!value || value.startsWith('--')) {
      throw new Error(`Missing value for --${rawKey}.`);
    }

    values.set(rawKey, value);
    if (!inlineValue) {
      index += 1;
    }
  }

  const courseRoot = values.get('course-root');
  if (!courseRoot) {
    throw new Error('Missing required --course-root.');
  }

  const chapter = parsePositiveInteger('chapter', values.get('chapter'));
  const lesson = parsePositiveInteger('lesson', values.get('lesson'));
  if (lesson && !chapter) {
    throw new Error('--lesson can only be used together with --chapter.');
  }

  const languageValue = (values.get('language') || 'bilingual') as SummaryLanguage;
  if (!['bilingual', 'match', 'english'].includes(languageValue)) {
    throw new Error('--language must be one of: bilingual, match, english.');
  }

  return {
    courseRoot: path.resolve(courseRoot),
    chapter,
    lesson,
    force: flags.has('force'),
    dryRun: flags.has('dry-run'),
    model: values.get('model') || DEFAULT_SUMMARY_MODEL,
    transcriptionModel: values.get('transcription-model') || DEFAULT_TRANSCRIPTION_MODEL,
    language: languageValue,
    withVisuals: flags.has('with-visuals'),
  };
}

async function pathExists(targetPath: string): Promise<boolean> {
  try {
    await access(targetPath);
    return true;
  } catch {
    return false;
  }
}

async function ensureDir(targetPath: string): Promise<void> {
  await mkdir(targetPath, { recursive: true });
}

async function statSignature(targetPath: string): Promise<string> {
  try {
    const fileStat = await stat(targetPath);
    return `${targetPath}|${fileStat.size}|${fileStat.mtimeMs}`;
  } catch {
    return `${targetPath}|missing`;
  }
}

async function ensureFfmpegAvailable(): Promise<void> {
  if (process.env.FFMPEG_PATH && existsSync(process.env.FFMPEG_PATH)) {
    ffmpegBinary = process.env.FFMPEG_PATH;
  } else {
    const locator = process.platform === 'win32'
      ? spawnSync('where.exe', ['ffmpeg.exe'], { encoding: 'utf8' })
      : spawnSync('which', ['ffmpeg'], { encoding: 'utf8' });
    const discoveredPath = locator.status === 0
      ? locator.stdout.split(/\r?\n/).map((line) => line.trim()).find(Boolean)
      : undefined;
    if (discoveredPath) {
      ffmpegBinary = discoveredPath;
    } else {
      const candidate = path.join(
        process.env.LOCALAPPDATA || '',
        'Microsoft',
        'WinGet',
        'Packages',
        'Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe',
        'ffmpeg-8.1-full_build',
        'bin',
        'ffmpeg.exe',
      );
      if (candidate && existsSync(candidate)) {
        ffmpegBinary = candidate;
      }
    }
  }

  const result = spawnSync(ffmpegBinary, ['-version'], { stdio: 'ignore' });
  if (result.error || result.status !== 0) {
    throw new Error('ffmpeg is not installed or not on PATH. Install ffmpeg, then rerun the summarizer.');
  }
}

async function runFfmpeg(args: string[], label: string): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const child = spawn(ffmpegBinary, ['-nostdin', ...args], {
      stdio: ['ignore', 'pipe', 'pipe'],
    });

    let stderr = '';
    child.stderr.on('data', (chunk: Buffer) => {
      stderr += chunk.toString();
    });

    child.on('error', (error) => {
      reject(new Error(`ffmpeg ${label} failed to start: ${error.message}`));
    });

    child.on('close', (code) => {
      if (code === 0) {
        resolve();
        return;
      }
      reject(new Error(`ffmpeg ${label} failed with exit code ${code}: ${stderr.trim()}`));
    });
  });
}

async function getMediaDurationSeconds(filePath: string): Promise<number> {
  const duration = await new Promise<number>((resolve, reject) => {
    const child = spawn(ffmpegBinary.replace(/ffmpeg(\.exe)?$/i, 'ffprobe$1'), [
      '-v', 'error',
      '-show_entries', 'format=duration',
      '-of', 'default=nw=1:nk=1',
      filePath,
    ], {
      stdio: ['ignore', 'pipe', 'pipe'],
    });

    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (chunk: Buffer) => {
      stdout += chunk.toString();
    });
    child.stderr.on('data', (chunk: Buffer) => {
      stderr += chunk.toString();
    });
    child.on('error', (error) => {
      reject(new Error(`ffprobe failed to start for ${path.basename(filePath)}: ${error.message}`));
    });
    child.on('close', (code) => {
      if (code !== 0) {
        reject(new Error(`ffprobe failed for ${path.basename(filePath)}: ${stderr.trim()}`));
        return;
      }
      const parsed = Number.parseFloat(stdout.trim());
      if (!Number.isFinite(parsed)) {
        reject(new Error(`ffprobe returned an invalid duration for ${path.basename(filePath)}.`));
        return;
      }
      resolve(parsed);
    });
  });

  return duration;
}

async function readManifest(manifestPath: string, options: CliOptions, courseRoot: string, courseTitle: string, summaryRoot: string): Promise<SummaryManifest> {
  if (await pathExists(manifestPath)) {
    try {
      const parsed = JSON.parse(await readFile(manifestPath, 'utf8')) as SummaryManifest;
      return parsed;
    } catch {
      // Fall back to a fresh manifest if the existing file is malformed.
    }
  }

  return {
    version: SUMMARY_VERSION,
    generatedAt: new Date().toISOString(),
    courseRoot,
    courseTitle,
    summaryRoot,
    options: {
      model: options.model,
      transcriptionModel: options.transcriptionModel,
      language: options.language,
      withVisuals: options.withVisuals,
    },
    lessons: [],
    documents: [],
  };
}

async function writeManifest(manifestPath: string, manifest: SummaryManifest): Promise<void> {
  manifest.generatedAt = new Date().toISOString();
  await ensureDir(path.dirname(manifestPath));
  await writeFile(manifestPath, JSON.stringify(manifest, null, 2), 'utf8');
}

async function discoverCourse(courseRoot: string, options: CliOptions): Promise<CourseNode> {
  const courseStats = await stat(courseRoot).catch(() => null);
  if (!courseStats?.isDirectory()) {
    throw new Error(`Course root was not found or is not a directory: ${courseRoot}`);
  }

  const entries = await readdir(courseRoot, { withFileTypes: true });
  const chapterDirs = entries
    .filter((entry) => entry.isDirectory() && /^(\d+)\s*-\s*/.test(entry.name))
    .map((entry) => {
      const match = entry.name.match(/^(\d+)\s*-\s*(.+)$/);
      return {
        order: match ? Number.parseInt(match[1], 10) : 999,
        title: sanitizePathSegment(match?.[2] || entry.name, entry.name),
        dir: path.join(courseRoot, entry.name),
      };
    })
    .sort((left, right) => left.order - right.order || left.title.localeCompare(right.title));

  const selectedChapters = options.chapter
    ? chapterDirs.filter((chapter) => chapter.order === options.chapter)
    : chapterDirs;

  if (options.chapter && !selectedChapters.length) {
    throw new Error(`Chapter ${options.chapter} was not found under ${courseRoot}.`);
  }

  const summaryRoot = path.join(courseRoot, '_Summaries');
  const chapters: ChapterNode[] = [];

  for (const chapter of selectedChapters) {
    const chapterEntries = await readdir(chapter.dir, { withFileTypes: true });
    const lessons = chapterEntries
      .filter((entry) => entry.isFile() && /\.mp4$/i.test(entry.name))
      .map((entry) => {
        const match = entry.name.match(/^(\d+)\s*-\s*(.+)\.mp4$/i);
        const lessonOrder = match ? Number.parseInt(match[1], 10) : 999;
        const lessonTitle = sanitizePathSegment(match?.[2] || entry.name.replace(/\.mp4$/i, ''), `Lesson ${lessonOrder}`);
        const videoPath = path.join(chapter.dir, entry.name);
        const lessonBase = entry.name.replace(/\.mp4$/i, '');
        const subtitlePaths = chapterEntries
          .filter((candidate) => candidate.isFile() && candidate.name.startsWith(`${lessonBase}.`) && /\.(vtt|srt)$/i.test(candidate.name))
          .map((candidate) => path.join(chapter.dir, candidate.name))
          .sort((left, right) => left.localeCompare(right));
        const lessonKey = `${formatIndex(chapter.order)}-${formatIndex(lessonOrder)}-${sanitizePathSegment(lessonTitle, 'lesson')}`;
        return {
          courseTitle: sanitizePathSegment(path.basename(courseRoot), path.basename(courseRoot)),
          chapterOrder: chapter.order,
          chapterTitle: chapter.title,
          lessonOrder,
          title: lessonTitle,
          videoPath,
          subtitlePaths,
          lessonKey,
          summaryJsonPath: path.join(summaryRoot, 'Intermediate', 'Lessons', `${lessonKey}.json`),
          summaryMarkdownPath: path.join(summaryRoot, 'Lessons', `${lessonKey}.md`),
        } as LessonNode;
      })
      .sort((left, right) => left.lessonOrder - right.lessonOrder || left.title.localeCompare(right.title));

    const selectedLessons = options.lesson
      ? lessons.filter((lesson) => lesson.lessonOrder === options.lesson)
      : lessons;

    if (options.lesson && options.chapter === chapter.order && !selectedLessons.length) {
      throw new Error(`Lesson ${options.lesson} was not found inside chapter ${chapter.order}.`);
    }

    if (selectedLessons.length > 0) {
      chapters.push({
        order: chapter.order,
        title: chapter.title,
        dir: chapter.dir,
        lessons: selectedLessons,
      });
    }
  }

  if (!chapters.length) {
    throw new Error(`No chapter folders with lesson videos were found under ${courseRoot}.`);
  }

  return {
    title: sanitizePathSegment(path.basename(courseRoot), path.basename(courseRoot)),
    courseRoot,
    summaryRoot,
    chapters,
  };
}

function parseTimestamp(value: string): number {
  const normalized = value.trim().replace(',', '.');
  const parts = normalized.split(':').map((part) => part.trim());
  if (parts.length < 2 || parts.length > 3) return Number.NaN;

  const secondsPart = Number.parseFloat(parts[parts.length - 1]);
  const minutesPart = Number.parseInt(parts[parts.length - 2] || '0', 10);
  const hoursPart = parts.length === 3 ? Number.parseInt(parts[0] || '0', 10) : 0;
  if (![secondsPart, minutesPart, hoursPart].every((number) => Number.isFinite(number))) {
    return Number.NaN;
  }
  return hoursPart * 3600 + minutesPart * 60 + secondsPart;
}

function parseVttContent(content: string): SourceCue[] {
  const lines = content.replace(/\r/g, '').split('\n');
  const cues: SourceCue[] = [];
  let index = 0;

  while (index < lines.length) {
    const line = lines[index].trim();
    if (!line || /^WEBVTT/i.test(line) || /^NOTE/i.test(line)) {
      index += 1;
      continue;
    }

    const timingLine = line.includes('-->') ? line : lines[index + 1]?.trim();
    if (!timingLine || !timingLine.includes('-->')) {
      index += 1;
      continue;
    }

    const [rawStart, rawEnd] = timingLine.split('-->').map((part) => part.trim().split(/\s+/)[0]);
    const startSeconds = parseTimestamp(rawStart);
    const endSeconds = parseTimestamp(rawEnd);
    if (!Number.isFinite(startSeconds) || !Number.isFinite(endSeconds)) {
      index += 1;
      continue;
    }

    const cueLines: string[] = [];
    index += line.includes('-->') ? 1 : 2;
    while (index < lines.length && lines[index].trim()) {
      cueLines.push(lines[index].trim().replace(/<[^>]+>/g, ''));
      index += 1;
    }

    const text = normalizeText(cueLines.join(' '));
    if (text) {
      cues.push({
        startSeconds,
        endSeconds,
        text,
        sourceType: 'subtitle',
      });
    }
    index += 1;
  }

  return cues;
}

function parseSrtContent(content: string): SourceCue[] {
  const blocks = content.replace(/\r/g, '').split('\n\n');
  const cues: SourceCue[] = [];

  for (const block of blocks) {
    const lines = block.split('\n').map((line) => line.trim()).filter(Boolean);
    if (lines.length < 2) continue;
    const timingLine = lines.find((line) => line.includes('-->'));
    if (!timingLine) continue;
    const [rawStart, rawEnd] = timingLine.split('-->').map((part) => part.trim().split(/\s+/)[0]);
    const startSeconds = parseTimestamp(rawStart);
    const endSeconds = parseTimestamp(rawEnd);
    if (!Number.isFinite(startSeconds) || !Number.isFinite(endSeconds)) continue;
    const text = normalizeText(lines.filter((line) => !line.includes('-->') && !/^\d+$/.test(line)).join(' '));
    if (!text) continue;
    cues.push({
      startSeconds,
      endSeconds,
      text,
      sourceType: 'subtitle',
    });
  }

  return cues;
}

async function loadBestSubtitleSource(subtitlePaths: string[]): Promise<LessonSource | null> {
  let best: LessonSource | null = null;

  for (const subtitlePath of subtitlePaths) {
    const content = await readFile(subtitlePath, 'utf8');
    const cues = /\.srt$/i.test(subtitlePath) ? parseSrtContent(content) : parseVttContent(content);
    const text = normalizeText(cues.map((cue) => cue.text).join(' '));
    if (!text) continue;
    const qualityNotes: string[] = [];
    const fileName = path.basename(subtitlePath).toLowerCase();
    if (fileName.includes('autogen') || fileName.includes('auto')) {
      qualityNotes.push('Subtitle filename suggests auto-generated captions.');
    }
    if (cues.length < 5) {
      qualityNotes.push('Very low cue count.');
    }
    if (text.length < 400) {
      qualityNotes.push('Very short subtitle text.');
    }

    const source: LessonSource = {
      sourceType: 'subtitle',
      subtitlePath,
      languageHint: detectPrimaryLanguage(text),
      autoGeneratedHint: qualityNotes.some((note) => note.toLowerCase().includes('auto-generated')),
      charCount: text.length,
      cueCount: cues.length,
      qualityNotes,
      cues,
    };

    if (!best || source.charCount > best.charCount) {
      best = source;
    }
  }

  return best;
}

function getOpenAiConfig() {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    throw new Error('OPENAI_API_KEY is required for non-dry-run summarization.');
  }
  return {
    apiKey,
    baseUrl: process.env.OPENAI_BASE_URL || 'https://api.openai.com/v1',
  };
}

function parseRetryDelayMs(response: Response, bodyText: string, attempt: number): number {
  const retryAfterHeader = response.headers.get('retry-after');
  if (retryAfterHeader) {
    const seconds = Number.parseFloat(retryAfterHeader);
    if (Number.isFinite(seconds) && seconds > 0) {
      return Math.ceil(seconds * 1000) + 1000;
    }
  }

  const messageMatch = bodyText.match(/Please try again in\s+([0-9.]+)s/i);
  if (messageMatch) {
    const seconds = Number.parseFloat(messageMatch[1]);
    if (Number.isFinite(seconds) && seconds > 0) {
      return Math.ceil(seconds * 1000) + 1000;
    }
  }

  return Math.min(120_000, 5_000 * 2 ** attempt);
}

async function openAiFetch(endpoint: string, init: RequestInit): Promise<Response> {
  const { apiKey, baseUrl } = getOpenAiConfig();

  for (let attempt = 0; attempt <= OPENAI_MAX_RETRIES; attempt += 1) {
    const headers = new Headers(init.headers || {});
    headers.set('Authorization', `Bearer ${apiKey}`);

    const response = await fetch(`${baseUrl}${endpoint}`, {
      ...init,
      headers,
    });

    if (response.ok) {
      return response;
    }

    const bodyText = await response.text();
    const isRateLimited = response.status === 429;
    if (!isRateLimited || attempt === OPENAI_MAX_RETRIES) {
      throw new Error(`OpenAI request failed: ${response.status} ${response.statusText} - ${bodyText}`);
    }

    const delayMs = parseRetryDelayMs(response, bodyText, attempt);
    console.warn(`OpenAI rate limit hit. Retrying in ${Math.ceil(delayMs / 1000)}s (attempt ${attempt + 1}/${OPENAI_MAX_RETRIES}).`);
    await sleep(delayMs);
  }

  throw new Error('OpenAI request failed after exhausting retries.');
}

async function callOpenAiJson<T>(
  model: string,
  schemaName: string,
  schema: Record<string, unknown>,
  messages: OpenAiChatMessage[],
): Promise<T> {
  const response = await openAiFetch('/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model,
      temperature: 0.2,
      messages,
      response_format: {
        type: 'json_schema',
        json_schema: {
          name: schemaName,
          strict: true,
          schema,
        },
      },
    }),
  });

  const payload = await response.json() as {
    choices?: Array<{ message?: { content?: string } }>;
  };
  const content = payload.choices?.[0]?.message?.content;
  if (!content) {
    throw new Error('OpenAI returned no structured content.');
  }
  return JSON.parse(content) as T;
}

async function callOpenAiMarkdown(model: string, messages: OpenAiChatMessage[]): Promise<string> {
  const response = await openAiFetch('/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model,
      temperature: 0.2,
      messages,
    }),
  });

  const payload = await response.json() as {
    choices?: Array<{ message?: { content?: string } }>;
  };
  const content = payload.choices?.[0]?.message?.content;
  if (!content) {
    throw new Error('OpenAI returned no markdown content.');
  }
  return content.trim();
}

async function transcribeAudioSegments(segmentPaths: string[], options: CliOptions): Promise<SourceCue[]> {
  const cues: SourceCue[] = [];

  for (let index = 0; index < segmentPaths.length; index += 1) {
    const segmentPath = segmentPaths[index];
    const buffer = await readFile(segmentPath);
    const segmentDuration = await getMediaDurationSeconds(segmentPath);
    const formData = new FormData();
    formData.append('model', options.transcriptionModel);
    formData.append('response_format', 'json');
    formData.append('file', new Blob([buffer]), path.basename(segmentPath));

    const response = await openAiFetch('/audio/transcriptions', {
      method: 'POST',
      body: formData,
    });

    const payload = await response.json() as {
      text?: string;
    };

    const offset = index * AUDIO_SEGMENT_SECONDS;
    const text = normalizeText(payload.text);
    if (text) {
      cues.push({
        startSeconds: offset,
        endSeconds: offset + Math.max(1, Math.ceil(segmentDuration)),
        text,
        sourceType: 'transcript',
      });
    }
  }

  return cues;
}

async function transcribeLessonAudio(videoPath: string, options: CliOptions): Promise<LessonSource> {
  const tempRoot = await mkdtemp(path.join(tmpdir(), 'course-summarize-'));
  try {
    const segmentPattern = path.join(tempRoot, 'audio-%03d.mp3');
    await runFfmpeg([
      '-y',
      '-loglevel', 'error',
      '-i', videoPath,
      '-vn',
      '-ac', '1',
      '-ar', '16000',
      '-b:a', '48k',
      '-f', 'segment',
      '-segment_time', String(AUDIO_SEGMENT_SECONDS),
      segmentPattern,
    ], `audio segmentation for ${path.basename(videoPath)}`);

    const segmentPaths = (await readdir(tempRoot, { withFileTypes: true }))
      .filter((entry) => entry.isFile() && /\.mp3$/i.test(entry.name))
      .map((entry) => path.join(tempRoot, entry.name))
      .sort((left, right) => left.localeCompare(right));

    if (!segmentPaths.length) {
      throw new Error(`No audio segments were produced for ${videoPath}`);
    }

    const cues = await transcribeAudioSegments(segmentPaths, options);
    const text = normalizeText(cues.map((cue) => cue.text).join(' '));
    return {
      sourceType: 'transcript',
      transcriptSegments: segmentPaths.map((segmentPath) => path.basename(segmentPath)),
      languageHint: detectPrimaryLanguage(text),
      autoGeneratedHint: false,
      charCount: text.length,
      cueCount: cues.length,
      qualityNotes: ['Transcript was generated from lesson audio because no usable subtitles were found.'],
      cues,
    };
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
}

async function buildLessonSource(lesson: LessonNode, options: CliOptions): Promise<LessonSource> {
  const subtitleSource = await loadBestSubtitleSource(lesson.subtitlePaths);
  if (subtitleSource && subtitleSource.charCount >= 400) {
    return subtitleSource;
  }
  return transcribeLessonAudio(lesson.videoPath, options);
}

function chunkCues(source: LessonSource): PreparedChunk[] {
  const chunks: PreparedChunk[] = [];
  let current: SourceCue[] = [];
  let currentTextLength = 0;
  let chunkIndex = 1;

  const flush = (): void => {
    if (!current.length) return;
    chunks.push({
      index: chunkIndex,
      startSeconds: current[0].startSeconds,
      endSeconds: current[current.length - 1].endSeconds,
      sourceType: source.sourceType,
      text: normalizeText(current.map((cue) => `${timestampFromSeconds(cue.startSeconds)} ${cue.text}`).join('\n')),
      cueCount: current.length,
    });
    chunkIndex += 1;
    current = [];
    currentTextLength = 0;
  };

  for (const cue of source.cues) {
    const cueLength = cue.text.length;
    const currentDuration = current.length
      ? cue.endSeconds - current[0].startSeconds
      : 0;
    const shouldFlush = current.length > 0
      && (currentTextLength + cueLength > DEFAULT_CHUNK_CHAR_LIMIT || currentDuration > DEFAULT_CHUNK_DURATION_SECONDS);
    if (shouldFlush) {
      flush();
    }
    current.push(cue);
    currentTextLength += cueLength;
  }

  flush();
  return chunks;
}

function lessonChunkSchema(): Record<string, unknown> {
  return {
    type: 'object',
    additionalProperties: false,
    properties: {
      conciseOverview: { type: 'string' },
      concepts: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            name: { type: 'string' },
            detail: { type: 'string' },
            evidence: { type: 'array', items: { type: 'string' } },
          },
          required: ['name', 'detail', 'evidence'],
        },
      },
      ingredients: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            name: { type: 'string' },
            detail: { type: 'string' },
            evidence: { type: 'array', items: { type: 'string' } },
          },
          required: ['name', 'detail', 'evidence'],
        },
      },
      techniques: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            name: { type: 'string' },
            detail: { type: 'string' },
            evidence: { type: 'array', items: { type: 'string' } },
          },
          required: ['name', 'detail', 'evidence'],
        },
      },
      tools: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            name: { type: 'string' },
            detail: { type: 'string' },
            evidence: { type: 'array', items: { type: 'string' } },
          },
          required: ['name', 'detail', 'evidence'],
        },
      },
      recipes: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            title: { type: 'string' },
            context: { type: 'string' },
            ingredients: { type: 'array', items: { type: 'string' } },
            quantities: { type: 'array', items: { type: 'string' } },
            steps: { type: 'array', items: { type: 'string' } },
            techniqueNotes: { type: 'array', items: { type: 'string' } },
            platingNotes: { type: 'array', items: { type: 'string' } },
            substitutions: { type: 'array', items: { type: 'string' } },
            evidence: { type: 'array', items: { type: 'string' } },
          },
          required: [
            'title',
            'context',
            'ingredients',
            'quantities',
            'steps',
            'techniqueNotes',
            'platingNotes',
            'substitutions',
            'evidence',
          ],
        },
      },
      caveats: { type: 'array', items: { type: 'string' } },
      facts: { type: 'array', items: { type: 'string' } },
      inferences: { type: 'array', items: { type: 'string' } },
      glossary: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            name: { type: 'string' },
            detail: { type: 'string' },
            evidence: { type: 'array', items: { type: 'string' } },
          },
          required: ['name', 'detail', 'evidence'],
        },
      },
    },
    required: [
      'conciseOverview',
      'concepts',
      'ingredients',
      'techniques',
      'tools',
      'recipes',
      'caveats',
      'facts',
      'inferences',
      'glossary',
    ],
  };
}

function lessonMergeSchema(): Record<string, unknown> {
  return {
    type: 'object',
    additionalProperties: false,
    properties: {
      conciseOverview: {
        type: 'object',
        additionalProperties: false,
        properties: {
          primary: { type: 'string' },
          english: { type: 'string' },
        },
        required: ['primary', 'english'],
      },
      detailedSummary: {
        type: 'object',
        additionalProperties: false,
        properties: {
          primary: { type: 'string' },
          english: { type: 'string' },
        },
        required: ['primary', 'english'],
      },
      keyTakeaways: { type: 'array', items: { type: 'string' } },
      ingredientNotes: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            name: { type: 'string' },
            detail: { type: 'string' },
            evidence: { type: 'array', items: { type: 'string' } },
          },
          required: ['name', 'detail', 'evidence'],
        },
      },
      techniqueNotes: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            name: { type: 'string' },
            detail: { type: 'string' },
            evidence: { type: 'array', items: { type: 'string' } },
          },
          required: ['name', 'detail', 'evidence'],
        },
      },
      equipmentNotes: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            name: { type: 'string' },
            detail: { type: 'string' },
            evidence: { type: 'array', items: { type: 'string' } },
          },
          required: ['name', 'detail', 'evidence'],
        },
      },
      recipes: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            title: { type: 'string' },
            context: { type: 'string' },
            ingredients: { type: 'array', items: { type: 'string' } },
            quantities: { type: 'array', items: { type: 'string' } },
            steps: { type: 'array', items: { type: 'string' } },
            techniqueNotes: { type: 'array', items: { type: 'string' } },
            platingNotes: { type: 'array', items: { type: 'string' } },
            substitutions: { type: 'array', items: { type: 'string' } },
            evidence: { type: 'array', items: { type: 'string' } },
          },
          required: [
            'title',
            'context',
            'ingredients',
            'quantities',
            'steps',
            'techniqueNotes',
            'platingNotes',
            'substitutions',
            'evidence',
          ],
        },
      },
      warnings: { type: 'array', items: { type: 'string' } },
      ambiguities: { type: 'array', items: { type: 'string' } },
      facts: { type: 'array', items: { type: 'string' } },
      inferences: { type: 'array', items: { type: 'string' } },
      glossary: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            name: { type: 'string' },
            detail: { type: 'string' },
            evidence: { type: 'array', items: { type: 'string' } },
          },
          required: ['name', 'detail', 'evidence'],
        },
      },
    },
    required: [
      'conciseOverview',
      'detailedSummary',
      'keyTakeaways',
      'ingredientNotes',
      'techniqueNotes',
      'equipmentNotes',
      'recipes',
      'warnings',
      'ambiguities',
      'facts',
      'inferences',
      'glossary',
    ],
  };
}

async function summarizeChunk(
  chunk: PreparedChunk,
  lesson: LessonNode,
  primaryLanguage: string,
  options: CliOptions,
): Promise<ChunkSummary> {
  const payload = await callOpenAiJson<Omit<ChunkSummary, 'chunkIndex' | 'startTimestamp' | 'endTimestamp'>>(options.model, 'lesson_chunk_summary', lessonChunkSchema(), [
    {
      role: 'system',
      content:
        'You summarize course content with high recall. Preserve cooking knowledge, ingredient behavior, technique nuance, cautions, and terminology. ' +
        'Do not invent quantities or steps. Keep facts separated from inferences. Evidence strings should cite timestamps or short source phrases when possible.',
    },
    {
      role: 'user',
      content: JSON.stringify({
        task: 'Summarize this lesson chunk into structured extraction data.',
        lesson: {
          courseTitle: lesson.courseTitle,
          chapterTitle: lesson.chapterTitle,
          lessonTitle: lesson.title,
        },
        outputRules: {
          requestedLanguageMode: options.language,
          primaryLanguage,
          optimizeFor: 'high recall',
          bilingualExpectation: options.language === 'bilingual',
        },
        chunk: {
          index: chunk.index,
          startTimestamp: timestampFromSeconds(chunk.startSeconds),
          endTimestamp: timestampFromSeconds(chunk.endSeconds),
          sourceType: chunk.sourceType,
          cueCount: chunk.cueCount,
          text: chunk.text,
        },
      }, null, 2),
    },
  ]);

  return {
    chunkIndex: chunk.index,
    startTimestamp: timestampFromSeconds(chunk.startSeconds),
    endTimestamp: timestampFromSeconds(chunk.endSeconds),
    ...payload,
  };
}

async function mergeLessonChunks(
  chunkSummaries: ChunkSummary[],
  lesson: LessonNode,
  source: LessonSource,
  options: CliOptions,
): Promise<LessonSummaryData> {
  const textForLanguageGuess = source.cues.map((cue) => cue.text).join(' ');
  const primaryLanguage = detectPrimaryLanguage(textForLanguageGuess);
  const payload = await callOpenAiJson<Omit<LessonSummaryData, 'metadata' | 'source' | 'timelineSegments'>>(options.model, 'lesson_merged_summary', lessonMergeSchema(), [
    {
      role: 'system',
      content:
        'You merge structured lesson chunk summaries into one high-recall lesson summary. ' +
        'Keep chronology, deduplicate repeated points, preserve concrete techniques and recipe details, and clearly separate facts from inference. ' +
        'For bilingual mode, provide the primary summary in the lesson language and an English companion summary.',
    },
    {
      role: 'user',
      content: JSON.stringify({
        task: 'Merge these structured chunk summaries into a final lesson summary.',
        lesson: {
          courseTitle: lesson.courseTitle,
          chapterTitle: lesson.chapterTitle,
          lessonTitle: lesson.title,
          primaryLanguage,
          requestedLanguageMode: options.language,
        },
        sourceQuality: {
          sourceType: source.sourceType,
          subtitlePath: source.subtitlePath,
          cueCount: source.cueCount,
          charCount: source.charCount,
          autoGeneratedHint: source.autoGeneratedHint,
          qualityNotes: source.qualityNotes,
        },
        chunks: chunkSummaries,
      }, null, 2),
    },
  ]);

  return {
    metadata: {
      version: SUMMARY_VERSION,
      courseTitle: lesson.courseTitle,
      chapterOrder: lesson.chapterOrder,
      chapterTitle: lesson.chapterTitle,
      lessonOrder: lesson.lessonOrder,
      lessonTitle: lesson.title,
      lessonKey: lesson.lessonKey,
      videoPath: lesson.videoPath,
      subtitlePaths: lesson.subtitlePaths,
      primaryLanguage,
      requestedLanguageMode: options.language,
    },
    source: {
      sourceType: source.sourceType,
      sourcePath: source.subtitlePath,
      transcriptSegments: source.transcriptSegments,
      cueCount: source.cueCount,
      charCount: source.charCount,
      languageHint: source.languageHint,
      autoGeneratedHint: source.autoGeneratedHint,
      qualityNotes: source.qualityNotes,
    },
    timelineSegments: chunkSummaries.map((chunk) => ({
      chunkIndex: chunk.chunkIndex,
      startTimestamp: chunk.startTimestamp,
      endTimestamp: chunk.endTimestamp,
      sourceType: source.sourceType,
      summary: chunk.conciseOverview,
    })),
    ...payload,
  };
}

function renderTopicEntries(entries: TopicEntry[]): string {
  if (!entries.length) return '_None extracted._';
  return entries.map((entry) => {
    const evidence = entry.evidence.length ? `\nEvidence: ${entry.evidence.join(' | ')}` : '';
    return `- **${entry.name}**: ${entry.detail}${evidence}`;
  }).join('\n');
}

function renderRecipeBlocks(recipes: RecipeEntry[]): string {
  if (!recipes.length) return '_No recipe blocks extracted._';
  return recipes.map((recipe) => {
    const sections = [
      `### ${recipe.title}`,
      recipe.context ? recipe.context : '',
      recipe.ingredients.length ? `Ingredients:\n${recipe.ingredients.map((value) => `- ${value}`).join('\n')}` : '',
      recipe.quantities.length ? `Quantities Stated:\n${recipe.quantities.map((value) => `- ${value}`).join('\n')}` : '',
      recipe.steps.length ? `Steps:\n${recipe.steps.map((value, index) => `${index + 1}. ${value}`).join('\n')}` : '',
      recipe.techniqueNotes.length ? `Technique Notes:\n${recipe.techniqueNotes.map((value) => `- ${value}`).join('\n')}` : '',
      recipe.platingNotes.length ? `Plating / Serving Notes:\n${recipe.platingNotes.map((value) => `- ${value}`).join('\n')}` : '',
      recipe.substitutions.length ? `Substitutions / Variations:\n${recipe.substitutions.map((value) => `- ${value}`).join('\n')}` : '',
      recipe.evidence.length ? `Evidence: ${recipe.evidence.join(' | ')}` : '',
    ].filter(Boolean);
    return sections.join('\n\n');
  }).join('\n\n');
}

function renderStringList(values: string[]): string {
  if (!values.length) return '_None recorded._';
  return values.map((value) => `- ${value}`).join('\n');
}

function renderLessonMarkdown(summary: LessonSummaryData): string {
  return [
    `# ${formatIndex(summary.metadata.chapterOrder)}.${formatIndex(summary.metadata.lessonOrder)} - ${summary.metadata.lessonTitle}`,
    '',
    '## Metadata',
    `- Course: ${summary.metadata.courseTitle}`,
    `- Chapter: ${formatIndex(summary.metadata.chapterOrder)} - ${summary.metadata.chapterTitle}`,
    `- Source Type: ${summary.source.sourceType}`,
    `- Primary Language: ${summary.metadata.primaryLanguage}`,
    `- Source Path: ${summary.source.sourcePath || summary.metadata.videoPath}`,
    '',
    '## Concise Overview',
    `Primary:\n${summary.conciseOverview.primary}`,
    '',
    `English:\n${summary.conciseOverview.english}`,
    '',
    '## Detailed Bilingual Summary',
    `Primary:\n${summary.detailedSummary.primary}`,
    '',
    `English:\n${summary.detailedSummary.english}`,
    '',
    '## Key Takeaways',
    renderStringList(summary.keyTakeaways),
    '',
    '## Ingredient Notes',
    renderTopicEntries(summary.ingredientNotes),
    '',
    '## Technique Notes',
    renderTopicEntries(summary.techniqueNotes),
    '',
    '## Equipment Notes',
    renderTopicEntries(summary.equipmentNotes),
    '',
    '## Recipe Blocks',
    renderRecipeBlocks(summary.recipes),
    '',
    '## Timeline Segments',
    summary.timelineSegments.map((segment) => `- **${segment.startTimestamp}-${segment.endTimestamp}**: ${segment.summary}`).join('\n') || '_No timeline segments._',
    '',
    '## Open Questions / Ambiguities',
    renderStringList(summary.ambiguities),
    '',
    '## Facts Stated in Lesson',
    renderStringList(summary.facts),
    '',
    '## Model Inferences / Normalizations',
    renderStringList(summary.inferences),
    '',
    '## Warnings / Caveats',
    renderStringList(summary.warnings),
    '',
    '## Glossary',
    renderTopicEntries(summary.glossary),
    '',
  ].join('\n');
}

function buildLessonSignature(lesson: LessonNode, options: CliOptions): Promise<string> {
  return Promise.all([
    statSignature(lesson.videoPath),
    ...lesson.subtitlePaths.map((subtitlePath) => statSignature(subtitlePath)),
  ]).then((parts) => sha256(JSON.stringify({
    lessonKey: lesson.lessonKey,
    files: parts,
    model: options.model,
    transcriptionModel: options.transcriptionModel,
    language: options.language,
    withVisuals: options.withVisuals,
    version: SUMMARY_VERSION,
  })));
}

async function summarizeLesson(
  lesson: LessonNode,
  options: CliOptions,
  manifest: SummaryManifest,
  manifestPath: string,
): Promise<LessonManifestEntry> {
  const sourceSignature = await buildLessonSignature(lesson, options);
  const existing = manifest.lessons.find((entry) => entry.lessonKey === lesson.lessonKey);
  const canSkip = !options.force
    && existing?.sourceSignature === sourceSignature
    && await pathExists(lesson.summaryJsonPath)
    && await pathExists(lesson.summaryMarkdownPath);

  if (canSkip) {
    const skipped: LessonManifestEntry = {
      lessonKey: lesson.lessonKey,
      lessonTitle: lesson.title,
      chapterOrder: lesson.chapterOrder,
      lessonOrder: lesson.lessonOrder,
      sourceSignature,
      summaryJsonPath: lesson.summaryJsonPath,
      summaryMarkdownPath: lesson.summaryMarkdownPath,
      sourceType: existing?.sourceType,
      status: 'skipped',
      updatedAt: new Date().toISOString(),
    };
    manifest.lessons = manifest.lessons.filter((entry) => entry.lessonKey !== lesson.lessonKey).concat(skipped);
    await writeManifest(manifestPath, manifest);
    return skipped;
  }

  if (options.dryRun) {
    const dryRun: LessonManifestEntry = {
      lessonKey: lesson.lessonKey,
      lessonTitle: lesson.title,
      chapterOrder: lesson.chapterOrder,
      lessonOrder: lesson.lessonOrder,
      sourceSignature,
      summaryJsonPath: lesson.summaryJsonPath,
      summaryMarkdownPath: lesson.summaryMarkdownPath,
      status: 'dry-run',
      updatedAt: new Date().toISOString(),
    };
    manifest.lessons = manifest.lessons.filter((entry) => entry.lessonKey !== lesson.lessonKey).concat(dryRun);
    await writeManifest(manifestPath, manifest);
    return dryRun;
  }

  try {
    const source = await buildLessonSource(lesson, options);
    const chunks = chunkCues(source);
    const primaryLanguage = detectPrimaryLanguage(source.cues.map((cue) => cue.text).join(' '));
    const chunkSummaries: ChunkSummary[] = [];

    for (const chunk of chunks) {
      chunkSummaries.push(await summarizeChunk(chunk, lesson, primaryLanguage, options));
    }

    const merged = await mergeLessonChunks(chunkSummaries, lesson, source, options);
    const markdown = renderLessonMarkdown(merged);

    await ensureDir(path.dirname(lesson.summaryJsonPath));
    await ensureDir(path.dirname(lesson.summaryMarkdownPath));
    await writeFile(lesson.summaryJsonPath, JSON.stringify(merged, null, 2), 'utf8');
    await writeFile(lesson.summaryMarkdownPath, markdown, 'utf8');

    const success: LessonManifestEntry = {
      lessonKey: lesson.lessonKey,
      lessonTitle: lesson.title,
      chapterOrder: lesson.chapterOrder,
      lessonOrder: lesson.lessonOrder,
      sourceSignature,
      summaryJsonPath: lesson.summaryJsonPath,
      summaryMarkdownPath: lesson.summaryMarkdownPath,
      sourceType: source.sourceType,
      status: 'success',
      updatedAt: new Date().toISOString(),
    };
    manifest.lessons = manifest.lessons.filter((entry) => entry.lessonKey !== lesson.lessonKey).concat(success);
    await writeManifest(manifestPath, manifest);
    return success;
  } catch (error) {
    const failed: LessonManifestEntry = {
      lessonKey: lesson.lessonKey,
      lessonTitle: lesson.title,
      chapterOrder: lesson.chapterOrder,
      lessonOrder: lesson.lessonOrder,
      sourceSignature,
      summaryJsonPath: lesson.summaryJsonPath,
      summaryMarkdownPath: lesson.summaryMarkdownPath,
      status: 'failed',
      updatedAt: new Date().toISOString(),
      error: stringifyError(error),
    };
    manifest.lessons = manifest.lessons.filter((entry) => entry.lessonKey !== lesson.lessonKey).concat(failed);
    await writeManifest(manifestPath, manifest);
    return failed;
  }
}

async function loadLessonSummaries(course: CourseNode): Promise<LessonSummaryData[]> {
  const summaries: LessonSummaryData[] = [];
  for (const chapter of course.chapters) {
    for (const lesson of chapter.lessons) {
      if (await pathExists(lesson.summaryJsonPath)) {
        summaries.push(JSON.parse(await readFile(lesson.summaryJsonPath, 'utf8')) as LessonSummaryData);
      }
    }
  }
  return summaries;
}

async function writeDocument(
  manifest: SummaryManifest,
  manifestPath: string,
  key: string,
  kind: DocumentKind,
  targetPath: string,
  signature: string,
  content: string,
  dryRun: boolean,
): Promise<void> {
  const existing = manifest.documents.find((entry) => entry.key === key);
  const canSkip = !dryRun && existing?.signature === signature && await pathExists(targetPath);
  if (canSkip) {
    const skipped: DocumentManifestEntry = {
      key,
      kind,
      signature,
      path: targetPath,
      status: 'skipped',
      updatedAt: new Date().toISOString(),
    };
    manifest.documents = manifest.documents.filter((entry) => entry.key !== key).concat(skipped);
    await writeManifest(manifestPath, manifest);
    return;
  }

  const status: LessonRunStatus = dryRun ? 'dry-run' : 'success';
  if (!dryRun) {
    await ensureDir(path.dirname(targetPath));
    await writeFile(targetPath, content, 'utf8');
  }
  manifest.documents = manifest.documents.filter((entry) => entry.key !== key).concat({
    key,
    kind,
    signature,
    path: targetPath,
    status,
    updatedAt: new Date().toISOString(),
  });
  await writeManifest(manifestPath, manifest);
}

async function generateChapterMarkdown(chapter: ChapterNode, lessons: LessonSummaryData[], options: CliOptions): Promise<string> {
  const compactLessons = lessons.map((lesson) => ({
    lessonKey: lesson.metadata.lessonKey,
    lessonTitle: lesson.metadata.lessonTitle,
    conciseOverview: lesson.conciseOverview,
    keyTakeaways: lesson.keyTakeaways.slice(0, 8),
    ingredientNames: lesson.ingredientNotes.slice(0, 12).map((entry) => entry.name),
    techniqueNames: lesson.techniqueNotes.slice(0, 12).map((entry) => entry.name),
    equipmentNames: lesson.equipmentNotes.slice(0, 10).map((entry) => entry.name),
    recipeTitles: lesson.recipes.slice(0, 8).map((recipe) => recipe.title),
    warnings: lesson.warnings.slice(0, 6),
    ambiguities: lesson.ambiguities.slice(0, 6),
  }));

  return callOpenAiMarkdown(options.model, [
    {
      role: 'system',
      content:
        'You write chapter rollups for course notes. Synthesize repeated themes, consolidate techniques and ingredients, and keep high recall. ' +
        'Do not simply concatenate lesson summaries. Clearly mark inferred normalization versus stated facts when important.',
    },
    {
      role: 'user',
      content: JSON.stringify({
        task: 'Write a detailed markdown chapter summary.',
        chapter: {
          order: chapter.order,
          title: chapter.title,
        },
        lessons: compactLessons,
      }, null, 2),
    },
  ]);
}

async function generateCourseOverviewMarkdown(
  course: CourseNode,
  chapterSummaries: Array<{ chapterOrder: number; chapterTitle: string; content: string }>,
  options: CliOptions,
): Promise<string> {
  return callOpenAiMarkdown(options.model, [
    {
      role: 'system',
      content:
        'You write a course master summary that preserves knowledge, structure, and recurring techniques. ' +
        'Group the material into themes and make the document useful as a long-term reference.',
    },
    {
      role: 'user',
      content: JSON.stringify({
        task: 'Write a markdown course overview that synthesizes all lesson summaries into one coherent reference document.',
        course: {
          title: course.title,
        },
        chapters: chapterSummaries,
      }, null, 2),
    },
  ]);
}

function uniqueTopicMap(entries: Array<{ lesson: LessonSummaryData; items: TopicEntry[] }>): Map<string, { detail: string[]; evidence: string[]; lessons: string[] }> {
  const map = new Map<string, { detail: string[]; evidence: string[]; lessons: string[] }>();
  for (const entry of entries) {
    for (const item of entry.items) {
      const key = item.name.toLowerCase();
      if (!map.has(key)) {
        map.set(key, { detail: [], evidence: [], lessons: [] });
      }
      const target = map.get(key)!;
      if (item.detail && !target.detail.includes(item.detail)) {
        target.detail.push(item.detail);
      }
      for (const evidence of item.evidence) {
        if (!target.evidence.includes(evidence)) {
          target.evidence.push(evidence);
        }
      }
      const lessonRef = `${formatIndex(entry.lesson.metadata.chapterOrder)}.${formatIndex(entry.lesson.metadata.lessonOrder)} ${entry.lesson.metadata.lessonTitle}`;
      if (!target.lessons.includes(lessonRef)) {
        target.lessons.push(lessonRef);
      }
    }
  }
  return map;
}

function renderIngredientsMarkdown(course: CourseNode, lessons: LessonSummaryData[]): string {
  const map = uniqueTopicMap(lessons.map((lesson) => ({ lesson, items: lesson.ingredientNotes })));
  const sections = Array.from(map.entries())
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, data]) => [
      `## ${name}`,
      data.detail.length ? data.detail.map((value) => `- ${value}`).join('\n') : '_No detail recorded._',
      data.lessons.length ? `Lessons: ${data.lessons.join('; ')}` : '',
      data.evidence.length ? `Evidence: ${data.evidence.join(' | ')}` : '',
    ].filter(Boolean).join('\n\n'));
  return [`# ${course.title} - Ingredients Reference`, '', ...sections].join('\n\n');
}

function renderTechniquesMarkdown(course: CourseNode, lessons: LessonSummaryData[]): string {
  const map = uniqueTopicMap(lessons.map((lesson) => ({ lesson, items: lesson.techniqueNotes })));
  const sections = Array.from(map.entries())
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, data]) => [
      `## ${name}`,
      data.detail.length ? data.detail.map((value) => `- ${value}`).join('\n') : '_No detail recorded._',
      data.lessons.length ? `Lessons: ${data.lessons.join('; ')}` : '',
      data.evidence.length ? `Evidence: ${data.evidence.join(' | ')}` : '',
    ].filter(Boolean).join('\n\n'));
  return [`# ${course.title} - Techniques Reference`, '', ...sections].join('\n\n');
}

function renderGlossaryMarkdown(course: CourseNode, lessons: LessonSummaryData[]): string {
  const map = uniqueTopicMap(lessons.map((lesson) => ({ lesson, items: lesson.glossary })));
  const sections = Array.from(map.entries())
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, data]) => [
      `## ${name}`,
      data.detail.length ? data.detail.map((value) => `- ${value}`).join('\n') : '_No definition recorded._',
      data.lessons.length ? `Lessons: ${data.lessons.join('; ')}` : '',
      data.evidence.length ? `Evidence: ${data.evidence.join(' | ')}` : '',
    ].filter(Boolean).join('\n\n'));
  return [`# ${course.title} - Glossary`, '', ...sections].join('\n\n');
}

function renderRecipesMarkdown(course: CourseNode, lessons: LessonSummaryData[]): string {
  const recipeSections: string[] = [];
  for (const lesson of lessons) {
    for (const recipe of lesson.recipes) {
      recipeSections.push([
        `## ${recipe.title}`,
        `Lesson: ${formatIndex(lesson.metadata.chapterOrder)}.${formatIndex(lesson.metadata.lessonOrder)} ${lesson.metadata.lessonTitle}`,
        recipe.context || '',
        recipe.ingredients.length ? `Ingredients:\n${recipe.ingredients.map((value) => `- ${value}`).join('\n')}` : '',
        recipe.quantities.length ? `Quantities:\n${recipe.quantities.map((value) => `- ${value}`).join('\n')}` : '',
        recipe.steps.length ? `Steps:\n${recipe.steps.map((value, index) => `${index + 1}. ${value}`).join('\n')}` : '',
        recipe.techniqueNotes.length ? `Technique Notes:\n${recipe.techniqueNotes.map((value) => `- ${value}`).join('\n')}` : '',
        recipe.platingNotes.length ? `Plating Notes:\n${recipe.platingNotes.map((value) => `- ${value}`).join('\n')}` : '',
        recipe.substitutions.length ? `Substitutions:\n${recipe.substitutions.map((value) => `- ${value}`).join('\n')}` : '',
        recipe.evidence.length ? `Evidence: ${recipe.evidence.join(' | ')}` : '',
      ].filter(Boolean).join('\n\n'));
    }
  }
  return [`# ${course.title} - Recipes Reference`, '', recipeSections.join('\n\n') || '_No recipes extracted._'].join('\n\n');
}

async function generateHigherLevelOutputs(course: CourseNode, options: CliOptions, manifest: SummaryManifest, manifestPath: string): Promise<void> {
  const lessons = await loadLessonSummaries(course);
  if (!lessons.length) {
    return;
  }

  const chapterSummaries: Array<{ chapterOrder: number; chapterTitle: string; content: string }> = [];

  for (const chapter of course.chapters) {
    const chapterLessons = lessons.filter((lesson) => lesson.metadata.chapterOrder === chapter.order);
    if (!chapterLessons.length) continue;
    const signature = sha256(JSON.stringify(chapterLessons.map((lesson) => [lesson.metadata.lessonKey, lesson.source.charCount, lesson.metadata.primaryLanguage])));
    const targetPath = path.join(course.summaryRoot, 'Chapters', `${formatIndex(chapter.order)} - ${chapter.title}.md`);
    const content = options.dryRun
      ? `# ${chapter.title}\n\n_Dry run: chapter summary would be generated here._\n`
      : await generateChapterMarkdown(chapter, chapterLessons, options);
    await writeDocument(manifest, manifestPath, `chapter:${chapter.order}`, 'chapter', targetPath, signature, content, options.dryRun);
    chapterSummaries.push({
      chapterOrder: chapter.order,
      chapterTitle: chapter.title,
      content,
    });
  }

  const overviewSignature = sha256(JSON.stringify(chapterSummaries.map((chapter) => [chapter.chapterOrder, chapter.content.length])));
  const overviewContent = options.dryRun
    ? `# ${course.title} - Course Overview\n\n_Dry run: course overview would be generated here._\n`
    : await generateCourseOverviewMarkdown(course, chapterSummaries, options);
  await writeDocument(
    manifest,
    manifestPath,
    'course:overview',
    'course',
    path.join(course.summaryRoot, 'Course Overview.md'),
    overviewSignature,
    overviewContent,
    options.dryRun,
  );

  const ingredientsSignature = sha256(JSON.stringify(lessons.map((lesson) => [lesson.metadata.lessonKey, lesson.ingredientNotes.length])));
  const techniquesSignature = sha256(JSON.stringify(lessons.map((lesson) => [lesson.metadata.lessonKey, lesson.techniqueNotes.length])));
  const recipesSignature = sha256(JSON.stringify(lessons.map((lesson) => [lesson.metadata.lessonKey, lesson.recipes.length])));
  const glossarySignature = sha256(JSON.stringify(lessons.map((lesson) => [lesson.metadata.lessonKey, lesson.glossary.length])));

  await writeDocument(
    manifest,
    manifestPath,
    'reference:ingredients',
    'ingredients',
    path.join(course.summaryRoot, 'Reference', 'Ingredients.md'),
    ingredientsSignature,
    renderIngredientsMarkdown(course, lessons),
    options.dryRun,
  );
  await writeDocument(
    manifest,
    manifestPath,
    'reference:techniques',
    'techniques',
    path.join(course.summaryRoot, 'Reference', 'Techniques.md'),
    techniquesSignature,
    renderTechniquesMarkdown(course, lessons),
    options.dryRun,
  );
  await writeDocument(
    manifest,
    manifestPath,
    'reference:recipes',
    'recipes',
    path.join(course.summaryRoot, 'Reference', 'Recipes.md'),
    recipesSignature,
    renderRecipesMarkdown(course, lessons),
    options.dryRun,
  );
  await writeDocument(
    manifest,
    manifestPath,
    'reference:glossary',
    'glossary',
    path.join(course.summaryRoot, 'Reference', 'Glossary.md'),
    glossarySignature,
    renderGlossaryMarkdown(course, lessons),
    options.dryRun,
  );
}

async function runSummarizer(options: CliOptions): Promise<void> {
  const course = await discoverCourse(options.courseRoot, options);
  const manifestPath = path.join(course.summaryRoot, 'manifest.json');
  const manifest = await readManifest(manifestPath, options, course.courseRoot, course.title, course.summaryRoot);

  if (!options.dryRun) {
    await ensureFfmpegAvailable();
    getOpenAiConfig();
  }

  if (options.withVisuals) {
    console.warn('Visual enrichment is not implemented in v1 yet. Continuing with subtitles/audio only.');
  }

  console.log(`Course: ${course.title}`);
  console.log(`Course root: ${course.courseRoot}`);
  console.log(`Summary root: ${course.summaryRoot}`);
  console.log(`Chapters selected: ${course.chapters.length}`);
  console.log(`Lessons selected: ${course.chapters.reduce((count, chapter) => count + chapter.lessons.length, 0)}`);

  await writeManifest(manifestPath, manifest);

  for (const chapter of course.chapters) {
    console.log(`\nChapter ${formatIndex(chapter.order)} - ${chapter.title}`);
    for (const lesson of chapter.lessons) {
      console.log(`  Summarizing ${formatIndex(chapter.order)}.${formatIndex(lesson.lessonOrder)} ${lesson.title}`);
      const entry = await summarizeLesson(lesson, options, manifest, manifestPath);
      if (entry.status === 'failed') {
        console.error(`    Failed: ${entry.error || 'Unknown error'}`);
      } else if (entry.status === 'skipped') {
        console.log('    Skipped: summary outputs already match the current source.');
      } else if (entry.status === 'dry-run') {
        console.log('    Dry run: summary outputs would be created.');
      } else {
        console.log(`    Done: ${lesson.summaryMarkdownPath}`);
      }
    }
  }

  await generateHigherLevelOutputs(course, options, manifest, manifestPath);
  console.log('\nSummarization finished.');
  console.log(`Manifest: ${manifestPath}`);
}

async function main(): Promise<void> {
  if (process.argv.includes('--help')) {
    printUsage();
    return;
  }

  const options = parseArgs(process.argv.slice(2));
  await runSummarizer(options);
}

void main().catch((error) => {
  console.error(stringifyError(error));
  process.exitCode = 1;
});
